### ISSUE TITLE
open web ui on printing

### ISSUE THREAD

**Issue by laverdone** [nokemono42/MP-Select-Mini-Web#7]
Open web ui when the printer is printing create a malfunction: the printer move out of printer area, problem was causated by the sendCMD on document ready:

The simple solution are move this command on new button in the web UI.

**sendCmd('M563 S4', 'Enable faster Wi-Fi file uploads');
sendCmd('G91', 'Set to Relative Positioning');**

**Comment by nokemono42** [comment]
This should have been fixed in Alpha 0.8 or 0.9, but I still agree. I'm adding SD card file functions and there is just too much being sent on page load to make it reliable. I'll work on a fix.

**Comment by nokemono42** [comment]
@laverdone This should have been fixed in Alpha 0.8 or 0.9, but I still agree. I'm adding SD card file functions and there is just too much being sent on page load to make it reliable. I'll work on a fix.

**Comment by nokemono42** [comment]
@laverdone Turns out Web Sockets isn’t that great for sending GCode. Now GCode is
sent via the REST API and the printer response is displayed via Web Sockets.

The bug would interrupt a print job has been fixed. G91 is only sent when needed, but Faster Wifi still loads on startup. It's just smarter when to send. I will still added a UI button, but my current workflow is just Refresh the page often.

**Comment by laverdone** [comment]
Ok,i'll try. Thanks
