### ISSUE TITLE
Alpha 0.9.1 on V2

### ISSUE THREAD

**Issue by Bubba2017** [nokemono42/MP-Select-Mini-Web#8]
V2, and Alpha 0.9.1
Temp will not change and will not update in webUI
Temp won't switch from Off to ON
After upload of gcode, start of print does not leave idle even though code is seen in window

**Comment by nokemono42** [comment]
@Bubba2017 The temp issues are odd since those functions are almost identical to the default webUI.

On page refresh does the browser console log any errors? Does the webUI response log show "Connection Established"?

The "print" GCode command behaves very differently then selecting a file for print from the LCD screen. I know the V2 firmware is a little different, but I'm not sure just how different.

**Comment by Bubba2017** [comment]
I reverted back to the factory Web UI.  I like where the new interface is going though.  Would be nice to see a countdown timer rather than a progress bar.

**Comment by joselopez650** [comment]
I just installed it on my v2 and it works perfectly.

**Comment by nokemono42** [comment]
@Bubba2017 Sadly timers aren't very practical and even the progress bar isn't a true indicator of time remaining. Most time estimators are based on layers remaining, but since layer complexity can vary the time estimates are never exact.

**Comment by Bubba2017** [comment]
Updated to Alpha 0.9.3 and the temps now show correctly for hotend and bed.  Non of the other controls seem to work.  i.e. home, sending g-code, fan speed, send print job etc.
